/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Dimension;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Katherine Rodriguez
 */
public class AdminPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form AdminPrincipal
     */
    public AdminPrincipal() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
    }
    
    void CentrarVentana(JInternalFrame frame){
        VentanaPrincipal.add(frame);
        Dimension dimension = VentanaPrincipal.getSize();
        Dimension DFrame = frame.getSize();
        frame.setLocation((dimension.width-DFrame.width)/2,(dimension.height-DFrame.height)/2);
        frame.show();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        VentanaPrincipal = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmRegistrarAlumno = new javax.swing.JMenuItem();
        jmActualizarAlumno = new javax.swing.JMenuItem();
        jmMatricular = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmRegistrarProfesor = new javax.swing.JMenuItem();
        jmActualizarProfesor = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jmRegistrarAsignatura = new javax.swing.JMenuItem();
        jmActualizarAsignatura = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jmSalir = new javax.swing.JMenuItem();

        jMenu4.setText("jMenu4");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        javax.swing.GroupLayout VentanaPrincipalLayout = new javax.swing.GroupLayout(VentanaPrincipal);
        VentanaPrincipal.setLayout(VentanaPrincipalLayout);
        VentanaPrincipalLayout.setHorizontalGroup(
            VentanaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        VentanaPrincipalLayout.setVerticalGroup(
            VentanaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        jMenu1.setText("Alumnos");

        jmRegistrarAlumno.setText("Registrar nuevo alumno");
        jmRegistrarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmRegistrarAlumnoActionPerformed(evt);
            }
        });
        jMenu1.add(jmRegistrarAlumno);

        jmActualizarAlumno.setText("Actualizar alumno");
        jmActualizarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmActualizarAlumnoActionPerformed(evt);
            }
        });
        jMenu1.add(jmActualizarAlumno);

        jmMatricular.setText("Matricular alumno");
        jmMatricular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmMatricularActionPerformed(evt);
            }
        });
        jMenu1.add(jmMatricular);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Profesores");

        jmRegistrarProfesor.setText("Registrar nuevo profesor");
        jmRegistrarProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmRegistrarProfesorActionPerformed(evt);
            }
        });
        jMenu2.add(jmRegistrarProfesor);

        jmActualizarProfesor.setText("Actualizar profesor");
        jmActualizarProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmActualizarProfesorActionPerformed(evt);
            }
        });
        jMenu2.add(jmActualizarProfesor);

        jMenuBar1.add(jMenu2);

        jMenu5.setText("Asignaturas");

        jmRegistrarAsignatura.setText("Registrar asignatura");
        jmRegistrarAsignatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmRegistrarAsignaturaActionPerformed(evt);
            }
        });
        jMenu5.add(jmRegistrarAsignatura);

        jmActualizarAsignatura.setText("Actualizar asignatura");
        jmActualizarAsignatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmActualizarAsignaturaActionPerformed(evt);
            }
        });
        jMenu5.add(jmActualizarAsignatura);

        jMenuBar1.add(jMenu5);

        jMenu3.setText("Salir");

        jmSalir.setText("Cerrar sesión");
        jmSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmSalirActionPerformed(evt);
            }
        });
        jMenu3.add(jmSalir);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(VentanaPrincipal, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(VentanaPrincipal, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmRegistrarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmRegistrarAlumnoActionPerformed
        RegistrarAlumnoForm registrarAlumno = new RegistrarAlumnoForm();
        CentrarVentana(registrarAlumno);
    }//GEN-LAST:event_jmRegistrarAlumnoActionPerformed

    private void jmActualizarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmActualizarAlumnoActionPerformed
        ActualizarAlumnoForm actualizarAlumno = new ActualizarAlumnoForm();
        CentrarVentana(actualizarAlumno);
    }//GEN-LAST:event_jmActualizarAlumnoActionPerformed

    private void jmRegistrarProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmRegistrarProfesorActionPerformed
        RegistrarProfesorForm registrarProfesor = new RegistrarProfesorForm();
        CentrarVentana(registrarProfesor);
    }//GEN-LAST:event_jmRegistrarProfesorActionPerformed

    private void jmActualizarProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmActualizarProfesorActionPerformed
        ActualizarProfesorForm actualizarProfesor = new ActualizarProfesorForm();
        CentrarVentana(actualizarProfesor);
    }//GEN-LAST:event_jmActualizarProfesorActionPerformed

    private void jmRegistrarAsignaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmRegistrarAsignaturaActionPerformed
        RegistrarAsignaturaForm resgistrarAsignatura = new RegistrarAsignaturaForm();
        CentrarVentana(resgistrarAsignatura);
    }//GEN-LAST:event_jmRegistrarAsignaturaActionPerformed

    private void jmActualizarAsignaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmActualizarAsignaturaActionPerformed
        ActualizarAsignaturaForm actualizarAsignatura = new ActualizarAsignaturaForm();
        CentrarVentana(actualizarAsignatura);
    }//GEN-LAST:event_jmActualizarAsignaturaActionPerformed

    private void jmMatricularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmMatricularActionPerformed
        MatricularAlumnoForm matricularAlumno = new MatricularAlumnoForm();
        CentrarVentana(matricularAlumno);
    }//GEN-LAST:event_jmMatricularActionPerformed

    private void jmSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmSalirActionPerformed
        int reply = JOptionPane.showConfirmDialog(null, "Esta seguro que desea cerrar sesión?", "Cerrar sesión", JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
            this.setVisible(false);
            new Principal().setVisible(true);
        }
    }//GEN-LAST:event_jmSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane VentanaPrincipal;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jmActualizarAlumno;
    private javax.swing.JMenuItem jmActualizarAsignatura;
    private javax.swing.JMenuItem jmActualizarProfesor;
    private javax.swing.JMenuItem jmMatricular;
    private javax.swing.JMenuItem jmRegistrarAlumno;
    private javax.swing.JMenuItem jmRegistrarAsignatura;
    private javax.swing.JMenuItem jmRegistrarProfesor;
    private javax.swing.JMenuItem jmSalir;
    // End of variables declaration//GEN-END:variables
}
