/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Dimension;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Katherine Rodriguez
 */
public class AlumnoPrincipal extends javax.swing.JFrame {

    private int id;
    /**
     * Creates new form AlumnoPrincipal
     */
    public AlumnoPrincipal(int id) {
        initComponents();
        this.id = id;
        this.setExtendedState(MAXIMIZED_BOTH);
    }
    
    void CentrarVentana(JInternalFrame frame){
        VentanaPrincipal.add(frame);
        Dimension dimension = VentanaPrincipal.getSize();
        Dimension DFrame = frame.getSize();
        frame.setLocation((dimension.width-DFrame.width)/2,(dimension.height-DFrame.height)/2);
        frame.show();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        VentanaPrincipal = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        ListaProfes = new javax.swing.JMenu();
        ListaProfesores = new javax.swing.JMenuItem();
        ListaCompa = new javax.swing.JMenuItem();
        ConsultarNota = new javax.swing.JMenuItem();
        ConsultarHorarios = new javax.swing.JMenuItem();
        ConsultarFaltas = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        javax.swing.GroupLayout VentanaPrincipalLayout = new javax.swing.GroupLayout(VentanaPrincipal);
        VentanaPrincipal.setLayout(VentanaPrincipalLayout);
        VentanaPrincipalLayout.setHorizontalGroup(
            VentanaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 464, Short.MAX_VALUE)
        );
        VentanaPrincipalLayout.setVerticalGroup(
            VentanaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 326, Short.MAX_VALUE)
        );

        ListaProfes.setText("Opciones");

        ListaProfesores.setText("Lista profesores");
        ListaProfesores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListaProfesoresActionPerformed(evt);
            }
        });
        ListaProfes.add(ListaProfesores);

        ListaCompa.setText("Lista compañeros");
        ListaCompa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListaCompaActionPerformed(evt);
            }
        });
        ListaProfes.add(ListaCompa);

        ConsultarNota.setText("Notas");
        ConsultarNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarNotaActionPerformed(evt);
            }
        });
        ListaProfes.add(ConsultarNota);

        ConsultarHorarios.setText("Horarios");
        ConsultarHorarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarHorariosActionPerformed(evt);
            }
        });
        ListaProfes.add(ConsultarHorarios);

        ConsultarFaltas.setText("Faltas de asistencia");
        ConsultarFaltas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarFaltasActionPerformed(evt);
            }
        });
        ListaProfes.add(ConsultarFaltas);

        jMenuBar1.add(ListaProfes);

        jMenu2.setText("Salir");

        jmSalir.setText("Cerrar sesión");
        jmSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmSalirActionPerformed(evt);
            }
        });
        jMenu2.add(jmSalir);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(VentanaPrincipal, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(VentanaPrincipal, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ListaProfesoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListaProfesoresActionPerformed
        ListaProfesAlumnoForm listaProfe = new ListaProfesAlumnoForm(id);
        CentrarVentana(listaProfe);
    }//GEN-LAST:event_ListaProfesoresActionPerformed

    private void ListaCompaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListaCompaActionPerformed
        ListaCompañerosForm listaCompa = new ListaCompañerosForm(id);
        CentrarVentana(listaCompa);
    }//GEN-LAST:event_ListaCompaActionPerformed

    private void ConsultarNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarNotaActionPerformed
        ListaNotasForm listaNotas = new ListaNotasForm(id);
        CentrarVentana(listaNotas);
    }//GEN-LAST:event_ConsultarNotaActionPerformed

    private void ConsultarFaltasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarFaltasActionPerformed
        ListaFaltasAlumnoForm listaFaltas = new ListaFaltasAlumnoForm(id);
        CentrarVentana(listaFaltas);
    }//GEN-LAST:event_ConsultarFaltasActionPerformed

    private void jmSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmSalirActionPerformed
        int reply = JOptionPane.showConfirmDialog(null, "Esta seguro que desea cerrar sesión?", "Cerrar sesión", JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
            this.setVisible(false);
            new Principal().setVisible(true);
        }   
    }//GEN-LAST:event_jmSalirActionPerformed

    private void ConsultarHorariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarHorariosActionPerformed
        ConsultarHorarioForm horarios = new ConsultarHorarioForm(id);
        CentrarVentana(horarios);
    }//GEN-LAST:event_ConsultarHorariosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlumnoPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlumnoPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlumnoPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlumnoPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ConsultarFaltas;
    private javax.swing.JMenuItem ConsultarHorarios;
    private javax.swing.JMenuItem ConsultarNota;
    private javax.swing.JMenuItem ListaCompa;
    private javax.swing.JMenu ListaProfes;
    private javax.swing.JMenuItem ListaProfesores;
    private javax.swing.JDesktopPane VentanaPrincipal;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jmSalir;
    // End of variables declaration//GEN-END:variables
}
