/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.ctrlAlumnos;
import control.ctrlProfesor;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import model.Profesor;

/**
 *
 * @author Katherine Rodriguez
 */
public class ListaProfeFrom extends javax.swing.JInternalFrame {

    private ctrlProfesor cp;
    private DefaultTableModel modelo;
    private int id;
    /**
     * Creates new form ListaProfe
     */
    public ListaProfeFrom(int id) {
        initComponents();
        cp = new ctrlProfesor();
        modelo = new DefaultTableModel();
        this.id = id;
        listar();
    }
    
    void listar(){
        ArrayList<Profesor> lista = cp.Listar();
        modelo = (DefaultTableModel)tabla.getModel();
        Object[] ob = new Object[2];
        for (int i = 0;i < lista.size(); i++){
            if(lista.get(i).getId() != id){
                ob[0] = lista.get(i).getNombre();
                ob[1] = lista.get(i).getApellidos();
                modelo.addRow(ob);
            }
        }
        tabla.setModel(modelo);                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();

        setClosable(true);
        setTitle("Lista de profesores");

        tabla.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Apellidos"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabla);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
