/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Dimension;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Katherine Rodriguez
 */
public class ProfePrincipal extends javax.swing.JFrame {

    private int id;
    /**
     * Creates new form ProfePrincipal
     */
    public ProfePrincipal(int id) {
        initComponents();
        this.id = id;
        this.setExtendedState(MAXIMIZED_BOTH);
    }
    
    void CentrarVentana(JInternalFrame frame){
        VentanaPrincipal.add(frame);
        Dimension dimension = VentanaPrincipal.getSize();
        Dimension DFrame = frame.getSize();
        frame.setLocation((dimension.width-DFrame.width)/2,(dimension.height-DFrame.height)/2);
        frame.show();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        VentanaPrincipal = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmListaAlumnos = new javax.swing.JMenuItem();
        jmAsignarNota = new javax.swing.JMenuItem();
        jmModificarNota = new javax.swing.JMenuItem();
        jmAsignarFalta = new javax.swing.JMenuItem();
        jmModificarFalta = new javax.swing.JMenuItem();
        jmListaFaltas = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmListaProfe = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jmSalir = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        javax.swing.GroupLayout VentanaPrincipalLayout = new javax.swing.GroupLayout(VentanaPrincipal);
        VentanaPrincipal.setLayout(VentanaPrincipalLayout);
        VentanaPrincipalLayout.setHorizontalGroup(
            VentanaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 445, Short.MAX_VALUE)
        );
        VentanaPrincipalLayout.setVerticalGroup(
            VentanaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 303, Short.MAX_VALUE)
        );

        jMenu1.setText("Alumnos");

        jmListaAlumnos.setText("Lista alumnos");
        jmListaAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmListaAlumnosActionPerformed(evt);
            }
        });
        jMenu1.add(jmListaAlumnos);

        jmAsignarNota.setText("Asignar nota");
        jmAsignarNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmAsignarNotaActionPerformed(evt);
            }
        });
        jMenu1.add(jmAsignarNota);

        jmModificarNota.setText("Modificar nota");
        jmModificarNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmModificarNotaActionPerformed(evt);
            }
        });
        jMenu1.add(jmModificarNota);

        jmAsignarFalta.setText("Asignar falta de asistencia");
        jmAsignarFalta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmAsignarFaltaActionPerformed(evt);
            }
        });
        jMenu1.add(jmAsignarFalta);

        jmModificarFalta.setText("Modificar falta de asistencia");
        jmModificarFalta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmModificarFaltaActionPerformed(evt);
            }
        });
        jMenu1.add(jmModificarFalta);

        jmListaFaltas.setText("Lista faltas de asistencia");
        jmListaFaltas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmListaFaltasActionPerformed(evt);
            }
        });
        jMenu1.add(jmListaFaltas);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Profesores");

        jmListaProfe.setText("Lista profesores");
        jmListaProfe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmListaProfeActionPerformed(evt);
            }
        });
        jMenu2.add(jmListaProfe);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Salir");

        jmSalir.setText("Cerrar sesión");
        jmSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmSalirActionPerformed(evt);
            }
        });
        jMenu4.add(jmSalir);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(VentanaPrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(VentanaPrincipal)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmListaAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmListaAlumnosActionPerformed
        ListaAlumnosForm listaAl = new ListaAlumnosForm(id);
        CentrarVentana(listaAl);
    }//GEN-LAST:event_jmListaAlumnosActionPerformed

    private void jmListaProfeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmListaProfeActionPerformed
        ListaProfeFrom listaPro = new ListaProfeFrom(id);
        CentrarVentana(listaPro);
    }//GEN-LAST:event_jmListaProfeActionPerformed

    private void jmAsignarNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmAsignarNotaActionPerformed
        AsignarNotaForm nota = new AsignarNotaForm(id);
        CentrarVentana(nota);
    }//GEN-LAST:event_jmAsignarNotaActionPerformed

    private void jmModificarNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmModificarNotaActionPerformed
        ModificarNotaForm modificarNota = new ModificarNotaForm(id);
        CentrarVentana(modificarNota);
    }//GEN-LAST:event_jmModificarNotaActionPerformed

    private void jmAsignarFaltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmAsignarFaltaActionPerformed
        RegistrarFaltaAsistenciaForm newFalta = new RegistrarFaltaAsistenciaForm(id);
        CentrarVentana(newFalta);
    }//GEN-LAST:event_jmAsignarFaltaActionPerformed

    private void jmModificarFaltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmModificarFaltaActionPerformed
        ModificarFaltaAsistenciaForm mofidicarFalta = new ModificarFaltaAsistenciaForm(id);
        CentrarVentana(mofidicarFalta);
    }//GEN-LAST:event_jmModificarFaltaActionPerformed

    private void jmListaFaltasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmListaFaltasActionPerformed
        ListaFaltasAsistencia listaFaltas = new ListaFaltasAsistencia(id);
        CentrarVentana(listaFaltas);
    }//GEN-LAST:event_jmListaFaltasActionPerformed

    private void jmSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmSalirActionPerformed
        int reply = JOptionPane.showConfirmDialog(null, "Esta seguro que desea cerrar sesión?", "Cerrar sesión", JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
            this.setVisible(false);
            new Principal().setVisible(true);
        }
    }//GEN-LAST:event_jmSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProfePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProfePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProfePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProfePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane VentanaPrincipal;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jmAsignarFalta;
    private javax.swing.JMenuItem jmAsignarNota;
    private javax.swing.JMenuItem jmListaAlumnos;
    private javax.swing.JMenuItem jmListaFaltas;
    private javax.swing.JMenuItem jmListaProfe;
    private javax.swing.JMenuItem jmModificarFalta;
    private javax.swing.JMenuItem jmModificarNota;
    private javax.swing.JMenuItem jmSalir;
    // End of variables declaration//GEN-END:variables
}
